config/routes.rb
Rails.application.routes.draw do
  resources :produtos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/produto.rb
class Produto < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: %i[ show edit update destroy ]

  # GET /produtos or /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1 or /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos or /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to produto_url(@produto), notice: "Produto was successfully created." }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1 or /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to produto_url(@produto), notice: "Produto was successfully updated." }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1 or /produtos/1.json
  def destroy
    @produto.destroy

    respond_to do |format|
      format.html { redirect_to produtos_url, notice: "Produto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def produto_params
      params.require(:produto).permit(:nome, :descricao, :estoque, :medida, :dt_entrada, :dt_validade)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/modal_helper.rb
module ModalHelper
    def confirmation_modal(&block)
      content_tag(:div, class: 'modal fade', id: 'confirmationModal', tabindex: '-1', role: 'dialog', aria: { labelledby: 'confirmationModalLabel', hidden: true }) do
        content_tag(:div, class: 'modal-dialog', role: 'document') do
          content_tag(:div, class: 'modal-content') do
            concat(content_tag(:div, class: 'modal-header') do
              concat(content_tag(:h5, 'Confirmação', class: 'modal-title', id: 'confirmationModalLabel'))
              concat(content_tag(:button, '×', type: 'button', class: 'close', data: { dismiss: 'modal' }, aria: { label: 'Fechar' }))
            end)
            concat(content_tag(:div, class: 'modal-body') do
              concat(content_tag(:p, 'Você tem certeza que deseja prosseguir com esta ação?'))
            end)
            concat(content_tag(:div, class: 'modal-footer') do
              concat(content_tag(:button, 'Cancelar', type: 'button', class: 'btn btn-secondary', data: { dismiss: 'modal' }))
              concat(capture(&block))
            end)
          end
        end
      end
    end
  end
  

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Almoxarifado</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link <%= current_page?(produtos_path) ? 'active' : '' %>" href="<%= produtos_path %>">Produtos</a>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Almoxarifado</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "layouts/navbar"  %>
    <%= yield %>

    <dialog id="turbo-confirm">
        <form method="dialog">
            <p>Tem certeza?</p>
          <div>
            <button value="cancel">Cancelar</button>
            <button value="confirm">confirmar</button>
          </div>
        </form>
    </dialog>
    
    </body>
</html>

app/views/produtos/_form.html.erb
<%= form_with(model: produto, class: "form") do |form| %>
  <% if produto.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
        <% produto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :nome, style: "display: block", class: "form-label" %>
        <%= form.text_field :nome, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :estoque, style: "display: block", class: "form-label" %>
        <%= form.number_field :estoque, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :medida, style: "display: block", class: "form-label" %>
        <%= form.text_field :medida, class: "form-control" %>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :Data_entrada, style: "display: block", class: "form-label" %>
        <%= form.date_field :dt_entrada, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :Data_validade, style: "display: block", class: "form-label" %>
        <%= form.date_field :dt_validade, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :descricao, style: "display: block", class: "form-label" %>
        <%= form.text_area :descricao, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/produtos/_formd.html.erb
<%= form_with(model: produto, class: "form") do |form| %>
  <% if produto.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
        <% produto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :nome, style: "display: block", class: "form-label" %>
        <%= form.text_field :nome, class: "form-control", disabled: true  %>
      </div>

      <div class="form-group">
        <%= form.label :estoque, style: "display: block", class: "form-label" %>
        <%= form.number_field :estoque, class: "form-control", disabled: true %>
      </div>

      <div class="form-group">
        <%= form.label :medida, style: "display: block", class: "form-label" %>
        <%= form.text_field :medida, class: "form-control", disabled: true %>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <%= form.label :Data_entrada, style: "display: block", class: "form-label" %>
        <%= form.date_field :dt_entrada, class: "form-control", disabled: true %>
      </div>

      <div class="form-group">
        <%= form.label :Data_validade, style: "display: block", class: "form-label" %>
        <%= form.date_field :dt_validade, class: "form-control", disabled: true %>
      </div>

      <div class="form-group">
        <%= form.label :descricao, style: "display: block", class: "form-label" %>
        <%= form.text_area :descricao, class: "form-control", disabled: true %>
      </div>
    </div>
  </div>
<% end %>

app/views/produtos/_produto.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Nome</th>
      <th scope="col">Descrição</th>
      <th scope="col">Estoque</th>
      <th scope="col">Medida</th>
      <th scope="col">Data entrada</th>
      <th scope="col">Data validade</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"><%= link_to produto.id, edit_produto_path(produto) %></th>
      <td><%= produto.nome %></td>
      <td><%= produto.descricao %></td>
      <td><%= produto.estoque %></td>
      <td><%= produto.medida %></td>
      <td><%= produto.dt_entrada %></td>
      <td><%= produto.dt_validade %></td>
      <td><%= button_to "🗑️", produto, method: :delete %></td>
      <td><%= button_to "Visualizar", produto, class: "btn btn-primary" %></td>
    </tr>
  </tbody>
</table>

app/views/produtos/edit.html.erb
<h1>Editing produto</h1>


<div>
  <%= link_to "Voltar", produtos_path, class: "btn btn-primary" %>
</div>

<br>

<%= render "form", produto: @produto %>

app/views/produtos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Produtos</h1>
<%= link_to "Novo produto", new_produto_path, class: "btn btn-primary" %>

<div id="produtos">
  
    <table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Nome</th>
      <th scope="col">Descrição</th>
      <th scope="col">Estoque</th>
      <th scope="col">Medida</th>
      <th scope="col">Data entrada</th>
      <th scope="col">Data validade</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  <% @produtos.each do |produto| %>
    <tr>
      <th scope="row"><%= link_to produto.id, edit_produto_path(produto) %></th>
      <td><%= produto.nome %></td>
      <td><%= produto.descricao %></td>
      <td><%= produto.estoque %></td>
      <td><%= produto.medida %></td>
      <td><%= produto.dt_entrada %></td>
      <td><%= produto.dt_validade %></td>
      <td><%= button_to "🗑️", produto, method: :delete, class: "btn btn-outline-secondary" %></td>
      <td><%= link_to "🔍", produto, class: "btn btn-outline-secondary" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/produtos/new.html.erb
<h1>Novo Produto</h1>

<div>
  <%= link_to "Voltar", produtos_path, class: "btn btn-primary" %>
</div>

<br>

<div>
  <%= render "form", produto: @produto %>
</div>

app/views/produtos/show.html.erb
<p style="color: green"><%= notice %></p>

<div>
  <%= link_to "Voltar", produtos_path, class: "btn btn-success"  %>
  <%= render "formd", produto: @produto %>
</div>